language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - npm install

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t reverseproxy .
  - docker build -t udagram-api-feed .
  - docker build -t udagram-frontend .
  - docker build -t udagram-api-user .
  - docker tag udagram-api-feed codevin/udagram-api-feed:v1
  - docker tag reverseproxy codevin/reverseproxy:v1
  - docker tag udagram-frontend codevin/udagram-frontend:v1
  - docker tag udagram-api-user codevin/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push codevin/udagram-api-feed:v1
  - docker push codevin/udagram-frontend:v1
  - docker push codevin/udagram-api-user:v1
  - docker push codevin/reverseproxy:v1

