# This file holds aws credential  in base64
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  credentials: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVo3Vk1WNlFOV0ZFVkVBR0IK