# This file holds aws credential  in base64
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  aws_access_key_id: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVo3Vk1WNlFOV0ZFVkVBR0IK
  aws_secret_access_key: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gQUtJQVo3Vk1WNlFOV0ZFVkVBR0IKYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gSjlVaG5TdGMwL0dWNTNBVm1iMjJjMHppTkJ3NHpRcnVKVmU2bXBzQgo=