apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-feed
  sessionAffinity: None
  type: ClusterIP
