apiVersion: v1  # app version
kind: Service
metadata:
  labels:
    app: backend-user
  name: backend-user-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend-user
  sessionAffinity: None
  type: ClusterIP
