apiVersion: v1
kind: Service
metadata:
  labels:
    app: udagram-frontend
  name: udagram-frontend-svc
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: udagram-frontend
  sessionAffinity: None
  type: ClusterIP
